version: '2'
services:

  app:
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    working_dir: /usr/share/nginx/html
    volumes:
      - ./application:/usr/share/nginx/html/
    environment:
      - DB_HOST=database

  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    working_dir: /usr/share/nginx/html
    volumes_from:
      - app
    ports:
      - ${SERVER_PORT}:80
      - ${SERVER_PORT_SSL}:443

  database:
    image: mariadb:10.2
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${SERVER_PORT_DB}:3306

volumes:
  dbdata: